global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.1.108:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.108:9100']